version: '3'
services:
  php_test:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/
  mailhog:
      image: mailhog/mailhog
      ports:
        - "1025:1025"
        - "8025:8025"